version: 2

project_name: taskagent

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - main: ./cmd/tasksh
    binary: taskagent
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - CLAUDE.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - "^build:"
      - "^refactor:"
      - "^style:"
      - Merge pull request
      - Merge branch

brews:
  - name: taskagent
    commit_author:
      name: Edmund Miller
      email: edmund.a.miller@gmail.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    directory: Formula
    homepage: https://github.com/edmundmiller/tasksh
    description: "Interactive AI-powered task review interface for Taskwarrior"
    license: MIT
    install: |
      bin.install "taskagent"
    test: |
      system "#{bin}/taskagent", "help"
    repository:
      owner: edmundmiller
      name: homebrew-taskagent
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"

release:
  github:
    owner: edmundmiller
    name: tasksh
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}}-v{{.Version}}"
  header: |
    ## What's Changed
  footer: |
    **Full Changelog**: https://github.com/edmundmiller/tasksh/compare/{{ .PreviousTag }}...{{ .Tag }}

announce:
  skip: true